/*
===============================================================================
Creator : Ceri Binding, University of South Wales ceri.binding@southwales.ac.uk
Project	: Any
Classes	: usw.usw.uri.RDF, usw.uri.RDFS, usw.uri.SKOS,  usw.uri.SKOSXL, 
          usw.uri.CRM, usw.uri.CRMEH, usw.uri.DC, usw.uri.DCTERMS, usw.uri.OWL
Summary	: Global constants of common namespace, entity and property URIs 
Example	: alert(usw.usw.uri.RDF.BAG) | alert(usw.usw.uri.RDF["BAG"])
		  either call returns "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"
License : http://creativecommons.org/publicdomain/zero/1.0/ 
===============================================================================
History	:
003 CFB 11/03/2015	Adapted from old STAR script. Added SKOS mapping properties
===============================================================================
*/
var usw = this.usw || {};
usw.uri = usw.uri || {};

// usw.uri.RDF
// usage: alert(usw.uri.RDF.BAG) | alert(usw.uri.RDF["BAG"])
// either call returns "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"
usw.uri.RDF = { NS: "http://www.w3.org/1999/02/22-rdf-syntax-ns#" };
usw.uri.RDF = {
    // entities
    XMLLITERAL: usw.uri.RDF.NS + "XMLLiteral",
    PROPERTY: usw.uri.RDF.NS + "Property",
    STATEMENT: usw.uri.RDF.NS + "Statement",
    BAG: usw.uri.RDF.NS + "Bag",
    SEQ: usw.uri.RDF.NS + "Seq",
    ALT: usw.uri.RDF.NS + "Alt",
    LIST: usw.uri.RDF.NS + "List",
    // properties
    TYPE: usw.uri.RDF.NS + "type",
    FIRST: usw.uri.RDF.NS + "first",
    REST: usw.uri.RDF.NS + "rest",
    VALUE: usw.uri.RDF.NS + "value",
    SUBJECT: usw.uri.RDF.NS + "subject",
    PREDICATE: usw.uri.RDF.NS + "predicate",
    OBJECT: usw.uri.RDF.NS + "object",
    ID: usw.uri.RDF.NS + "ID"
};

// usw.uri.RDFS
// usage: alert(usw.uri.RDFS.LITERAL) | alert(usw.uri.RDFS["LITERAL"])
// either call returns "http://www.w3.org/2000/01/rdf-schema#Literal"
usw.uri.RDFS = { NS: "http://www.w3.org/2000/01/rdf-schema#" };
usw.uri.RDFS = {
    // entities
    RESOURCE: usw.uri.RDFS.NS + "Resource",
    LITERAL: usw.uri.RDFS.NS + "Literal",
    CLASS: usw.uri.RDFS.NS + "Class",
    DATATYPE: usw.uri.RDFS.NS + "Datatype",
    CONTAINER: usw.uri.RDFS.NS + "Container",
    CONTAINERMEMBERSHIPPROPERTY: usw.uri.RDFS.NS + "ContainerMembershipProperty",
    // properties
    SUBCLASSOF: usw.uri.RDFS.NS + "subClassOf",
    SUBPROPERTYOF: usw.uri.RDFS.NS + "subPropertyOf",
    DOMAIN: usw.uri.RDFS.NS + "domain",
    RANGE: usw.uri.RDFS.NS + "range",
    LABEL: usw.uri.RDFS.NS + "label",
    COMMENT: usw.uri.RDFS.NS + "comment",
    MEMBER: usw.uri.RDFS.NS + "member",
    SEEALSO: usw.uri.RDFS.NS + "seeAlso",
    ISDEFINEDBY: usw.uri.RDFS.NS + "isDefinedBy"
};

// usw.uri.SKOS
// usage: alert(usw.uri.SKOS.CONCEPT)OR alert(usw.uri.SKOS["CONCEPT"])
// either call returns "http://www.w3.org/2004/02/skos/core#Concept"		
usw.uri.SKOS = { NS: "http://www.w3.org/2004/02/skos/core#" };
usw.uri.SKOS = {
    // entities
    COLLECTABLEPROPERTY: usw.uri.SKOS.NS + "CollectableProperty",
    COLLECTION: usw.uri.SKOS.NS + "Collection",
    CONCEPT: usw.uri.SKOS.NS + "Concept",
    CONCEPTSCHEME: usw.uri.SKOS.NS + "ConceptScheme",
    ORDEREDCOLLECTION: usw.uri.SKOS.NS + "OrderedCollection",
    // properties
    ALTLABEL: usw.uri.SKOS.NS + "altLabel",
    ALTSYMBOL: usw.uri.SKOS.NS + "altSymbol",
    BROADER: usw.uri.SKOS.NS + "broader",
    CHANGENOTE: usw.uri.SKOS.NS + "changeNote",
    DEFINITION: usw.uri.SKOS.NS + "definition",
    EDITORIALNOTE: usw.uri.SKOS.NS + "editorialNote",
    EXAMPLE: usw.uri.SKOS.NS + "example",
    HASTOPCONCEPT: usw.uri.SKOS.NS + "hasTopConcept",
    HIDDENLABEL: usw.uri.SKOS.NS + "hiddenLabel",
    HISTORYNOTE: usw.uri.SKOS.NS + "historyNote",
    INSCHEME: usw.uri.SKOS.NS + "inScheme",
    ISPRIMARYSUBJECTOF: usw.uri.SKOS.NS + "isPrimarySubjectOf",
    ISSUBJECTOF: usw.uri.SKOS.NS + "isSubjectOf",
    MEMBER: usw.uri.SKOS.NS + "member",
    MEMBERLIST: usw.uri.SKOS.NS + "memberList",
    NARROWER: usw.uri.SKOS.NS + "narrower",
    NOTE: usw.uri.SKOS.NS + "note",
    PREFLABEL: usw.uri.SKOS.NS + "prefLabel",
    PREFSYMBOL: usw.uri.SKOS.NS + "prefSymbol",
    PRIMARYSUBJECT: usw.uri.SKOS.NS + "primarySubject",
    RELATED: usw.uri.SKOS.NS + "related",
    SCOPENOTE: usw.uri.SKOS.NS + "scopeNote",
    SEMANTICRELATION: usw.uri.SKOS.NS + "semanticRelation",
    SUBJECT: usw.uri.SKOS.NS + "subject",
    SUBJECTINDICATOR: usw.uri.SKOS.NS + "subjectIndicator",
    SYMBOL: usw.uri.SKOS.NS + "symbol",
    // mapping properties
    EXACTMATCH: usw.uri.SKOS.NS + "exactMatch",
    CLOSEMATCH: usw.uri.SKOS.NS + "closeMatch",
    BROADMATCH: usw.uri.SKOS.NS + "broadMatch",
    NARROWMATCH: usw.uri.SKOS.NS + "narrowMatch",
    RELATEDMATCH: usw.uri.SKOS.NS + "relatedMatch"
};

// usw.uri.SKOSXL
// usage: alert(usw.uri.SKOSXL.PREFLABEL)OR alert(usw.uri.SKOSXL["PREFLABEL"])
// either call returns "http://www.w3.org/2008/05/skos-xl#Label"		
usw.uri.SKOSXL = { NS: "http://www.w3.org/2008/05/skos-xl#" };
usw.uri.SKOSXL = {
    // entities
    LABEL: usw.uri.SKOSXL.NS + "Label",
    // properties
    PREFLABEL: usw.uri.SKOSXL.NS + "prefLabel",
    ALTLABEL: usw.uri.SKOSXL.NS + "altLabel",
    HIDDENLABEL: usw.uri.SKOSXL.NS + "hiddenLabel",
    LABELRELATION: usw.uri.SKOSXL.NS + "labelRelation",
    LITERALFORM: usw.uri.SKOSXL.NS + "literalForm"
};

// usw.uri.CRMEH
// usage: alert(usw.uri.CRMEH.EHE0001) | alert(usw.uri.CRMEH["EHE0001"])
// either call returns "http://purl.org/crmeh#EHE0001_EHProject"	
usw.uri.CRMEH = { NS: "http://purl.org/crmeh#" };
usw.uri.CRMEH = {
    // entities
    EHE0001: usw.uri.CRMEH.NS + "EHE0001_EHProject",
    EHE0002: usw.uri.CRMEH.NS + "EHE0002_ArchaeologicalSite",
    EHE0003: usw.uri.CRMEH.NS + "EHE0003_AreaOfInvestigation",
    EHE0004: usw.uri.CRMEH.NS + "EHE0004_SiteSubDivision",
    EHE0005: usw.uri.CRMEH.NS + "EHE0005_Group",
    EHE0006: usw.uri.CRMEH.NS + "EHE0006_GroupStuff",
    EHE0007: usw.uri.CRMEH.NS + "EHE0007_Context",
    EHE0008: usw.uri.CRMEH.NS + "EHE0008_ContextStuff",
    EHE0009: usw.uri.CRMEH.NS + "EHE0009_ContextFind",
    EHE0010: usw.uri.CRMEH.NS + "EHE0010_BulkFind",
    EHE0011: usw.uri.CRMEH.NS + "EHE0011_GroupEventRecord",
    EHE0012: usw.uri.CRMEH.NS + "EHE0012_ContextEventRecord",
    EHE0013: usw.uri.CRMEH.NS + "EHE0013_ContextSheet",
    EHE0014: usw.uri.CRMEH.NS + "EHE0014_ContextFindProductionEventRecord",
    EHE0015: usw.uri.CRMEH.NS + "EHE0015_ContextFindUseEventRecord",
    EHE0016: usw.uri.CRMEH.NS + "EHE0016_RecordDrawing",
    EHE0017: usw.uri.CRMEH.NS + "EHE0017_RecordPhotograph",
    EHE0018: usw.uri.CRMEH.NS + "EHE0018_ContextSample",
    EHE0019: usw.uri.CRMEH.NS + "EHE0019_AreaOfInvestigationDepiction",
    EHE0020: usw.uri.CRMEH.NS + "EHE0020_BulkFindComponentCount",
    EHE0021: usw.uri.CRMEH.NS + "EHE0021_EHProjectTimespan",
    EHE0022: usw.uri.CRMEH.NS + "EHE0022_ContextDepiction",
    EHE0023: usw.uri.CRMEH.NS + "EHE0023_ContextEventRecordNote",
    EHE0024: usw.uri.CRMEH.NS + "EHE0024_ContextEventRecordNoteType",
    EHE0025: usw.uri.CRMEH.NS + "EHE0025_ContextEventTimespan",
    EHE0026: usw.uri.CRMEH.NS + "EHE0026_ContextEventTimespanAppellation",
    EHE0027: usw.uri.CRMEH.NS + "EHE0027_ContextFindConditionAssessmentEventTimespan",
    EHE0028: usw.uri.CRMEH.NS + "EHE0028_ContextFindConditionAssessmentEventType",
    EHE0029: usw.uri.CRMEH.NS + "EHE0029_ContextFindConditionState",
    EHE0030: usw.uri.CRMEH.NS + "EHE0030_ContextFindMaterial",
    EHE0031: usw.uri.CRMEH.NS + "EHE0031_ContextFindMeasurement",
    EHE0032: usw.uri.CRMEH.NS + "EHE0032_ContextFindMeasurementEventTimespan",
    EHE0033: usw.uri.CRMEH.NS + "EHE0033_ContextFindMeasurementEventType",
    EHE0034: usw.uri.CRMEH.NS + "EHE0034_ContextFindMeasurementUnit",
    EHE0035: usw.uri.CRMEH.NS + "EHE0035_ContextFindMeasurementValue",
    EHE0036: usw.uri.CRMEH.NS + "EHE0036_ContextFindProductionEventRecordNote",
    EHE0037: usw.uri.CRMEH.NS + "EHE0037_ContextFindProductionEventRecordNoteType",
    EHE0038: usw.uri.CRMEH.NS + "EHE0038_ContextFindProductionEventTimespan",
    EHE0039: usw.uri.CRMEH.NS + "EHE0039_ContextFindProductionEventTimespanAppellation",
    EHE0040: usw.uri.CRMEH.NS + "EHE0040_ContextFindTreatmentLocation",
    EHE0041: usw.uri.CRMEH.NS + "EHE0041_ContextFindTreatmentProcedure",
    EHE0042: usw.uri.CRMEH.NS + "EHE0042_ContextFindTreatmentType",
    EHE0043: usw.uri.CRMEH.NS + "EHE0043_ContextFindUID",
    EHE0044: usw.uri.CRMEH.NS + "EHE0044_ContextFindUseEventRecordNote",
    EHE0045: usw.uri.CRMEH.NS + "EHE0045_ContextFindUseEventRecordNoteType",
    EHE0046: usw.uri.CRMEH.NS + "EHE0046_ContextNote",
    EHE0047: usw.uri.CRMEH.NS + "EHE0047_ContextNoteType",
    EHE0048: usw.uri.CRMEH.NS + "EHE0048_ContextRecord",
    EHE0049: usw.uri.CRMEH.NS + "EHE0049_ContextSampleMeasurement",
    EHE0050: usw.uri.CRMEH.NS + "EHE0050_ContextSampleMeasurementType",
    EHE0051: usw.uri.CRMEH.NS + "EHE0051_ContextSampleMeasurementUnit",
    EHE0052: usw.uri.CRMEH.NS + "EHE0052_ContextSampleMeasurementValue",
    EHE0053: usw.uri.CRMEH.NS + "EHE0053_ContextSampleType",
    EHE0054: usw.uri.CRMEH.NS + "EHE0054_ContextStuffMeasurement",
    EHE0055: usw.uri.CRMEH.NS + "EHE0055_ContextStuffMeasurementEventTimespan",
    EHE0056: usw.uri.CRMEH.NS + "EHE0056_ContextStuffMeasurementEventType",
    EHE0057: usw.uri.CRMEH.NS + "EHE0057_ContextStuffMeasurementUnit",
    EHE0058: usw.uri.CRMEH.NS + "EHE0058_ContextStuffMeasurementValue",
    EHE0059: usw.uri.CRMEH.NS + "EHE0059_ContextStuffNote",
    EHE0060: usw.uri.CRMEH.NS + "EHE0060_ContextStuffNoteType",
    EHE0061: usw.uri.CRMEH.NS + "EHE0061_ContextUID",
    EHE0062: usw.uri.CRMEH.NS + "EHE0062_FlotationSample",
    EHE0063: usw.uri.CRMEH.NS + "EHE0063_FlotationSampleResidue",
    EHE0064: usw.uri.CRMEH.NS + "EHE0064_FlotationSampleResidueMeasurement",
    EHE0065: usw.uri.CRMEH.NS + "EHE0065_FlotationSampleResidueMeasurementUnit",
    EHE0066: usw.uri.CRMEH.NS + "EHE0066_FlotationSampleResidueMeasurementValue",
    EHE0067: usw.uri.CRMEH.NS + "EHE0067.FlotationSampleResidueType",
    EHE0068: usw.uri.CRMEH.NS + "EHE0068_GroupEventRecordNote",
    EHE0069: usw.uri.CRMEH.NS + "EHE0069_GroupEventRecordNoteType",
    EHE0070: usw.uri.CRMEH.NS + "EHE0070_GroupEventTimespan",
    EHE0071: usw.uri.CRMEH.NS + "EHE0071_GroupEventTimespanAppellation",
    EHE0072: usw.uri.CRMEH.NS + "EHE0072_GroupEventType",
    EHE0073: usw.uri.CRMEH.NS + "EHE0073_GroupingPhasingProcedure",
    EHE0074: usw.uri.CRMEH.NS + "EHE0074_IdentifiedFeature",
    EHE0075: usw.uri.CRMEH.NS + "EHE0075_IdentifiedFeatureDepiction",
    EHE0076: usw.uri.CRMEH.NS + "EHE0076_ProjectDesign",
    EHE0077: usw.uri.CRMEH.NS + "EHE0077_ProjectTeamMember",
    EHE0078: usw.uri.CRMEH.NS + "EHE0078_ProjectTeamMemberRole",
    EHE0079: usw.uri.CRMEH.NS + "EHE0079_RecordDrawingNote",
    EHE0080: usw.uri.CRMEH.NS + "EHE0080_RecordDrawingNoteType",
    EHE0081: usw.uri.CRMEH.NS + "EHE0081_RecordDrawingReferenceType",
    EHE0082: usw.uri.CRMEH.NS + "EHE0082_RecordDrawingSheet",
    EHE0083: usw.uri.CRMEH.NS + "EHE0083_RecordPhotographNote",
    EHE0084: usw.uri.CRMEH.NS + "EHE0084_RecordPhotographNoteType",
    EHE0085: usw.uri.CRMEH.NS + "EHE0085_RecordPhotographReferenceType",
    EHE0086: usw.uri.CRMEH.NS + "EHE0086_ResponsibleAgent",
    EHE0087: usw.uri.CRMEH.NS + "EHE0087_SiteSubDivisionAppellation",
    EHE0088: usw.uri.CRMEH.NS + "EHE0088_SiteSubDivisionDepiction",
    EHE0089: usw.uri.CRMEH.NS + "EHE0089_StorageLocation",
    EHE0090: usw.uri.CRMEH.NS + "EHE0090_SurveyDataset",
    EHE0091: usw.uri.CRMEH.NS + "EHE0091_Timestamp",
    EHE0092: usw.uri.CRMEH.NS + "EHE0092_GroupUID",
    EHE0093: usw.uri.CRMEH.NS + "EHE0093_GroupDepiction",
    EHE0094: usw.uri.CRMEH.NS + "EHE0094_FlotationSampleResidueMeasurementType",
    EHE0095: usw.uri.CRMEH.NS + "EHE0095_ContextFindProductionEventLocation",
    EHE0096: usw.uri.CRMEH.NS + "EHE0096_ContextFindGeneralUse",
    EHE0097: usw.uri.CRMEH.NS + "EHE0097_ContextFindIntendedUse",
    EHE0098: usw.uri.CRMEH.NS + "EHE0098_ContextFindExcavationEventTimespan",
    EHE0099: usw.uri.CRMEH.NS + "EHE0099_ContextFindUseEventTimespan",
    EHE1001: usw.uri.CRMEH.NS + "EHE1001_ContextEvent",
    EHE1002: usw.uri.CRMEH.NS + "EHE1002_ContextFindProductionEvent",
    EHE1003: usw.uri.CRMEH.NS + "EHE1003_GroupEvent",
    EHE1004: usw.uri.CRMEH.NS + "EHE1004_ContextFindDepositionEvent",
    EHE1005: usw.uri.CRMEH.NS + "EHE1005_ContextFindUseEvent",
    EHE2001: usw.uri.CRMEH.NS + "EHE2001_ContextExcavationEvent",
    EHE2002: usw.uri.CRMEH.NS + "EHE2002_ContextFindClassificationEvent",
    EHE2003: usw.uri.CRMEH.NS + "EHE2003_ContextFindTreatmentEvent",
    EHE2004: usw.uri.CRMEH.NS + "EHE2004_GroupingPhasingEvent",
    EHE2005: usw.uri.CRMEH.NS + "EHE2005_ContextFindDatingEvent",
    EHE2006: usw.uri.CRMEH.NS + "EHE2006_ContextSamplingEvent",
    EHE2007: usw.uri.CRMEH.NS + "EHE2007_SurveyEvent",
    EHE2008: usw.uri.CRMEH.NS + "EHE2008_ProcessSurveyDatasetEvent",
    EHE2009: usw.uri.CRMEH.NS + "EHE2009_TransferObjectEvent",
    EHE2010: usw.uri.CRMEH.NS + "EHE2010_DepictionEvent",
    EHE2011: usw.uri.CRMEH.NS + "EHE2011_BulkFindItemRemovalEvent",
    EHE2012: usw.uri.CRMEH.NS + "EHE2012_ContextFindConditionAssessmentEvent",
    EHE2013: usw.uri.CRMEH.NS + "EHE2013_ContextFindIdentifierAssignmentEvent",
    EHE2014: usw.uri.CRMEH.NS + "EHE2014_ContextFindUseAssessmentEvent",
    EHE2015: usw.uri.CRMEH.NS + "EHE2015_ContextSampleProcessingEvent",
    EHE2016: usw.uri.CRMEH.NS + "EHE2016_ContextStuffMeasurementEvent",
    EHE2017: usw.uri.CRMEH.NS + "EHE2017_FlotationSampleProcessingEvent",
    EHE2018: usw.uri.CRMEH.NS + "EHE2018_FlotationSampleResidueProcessingEvent",
    EHE2019: usw.uri.CRMEH.NS + "EHE2019_SimpleNameAssignmentEvent",
    EHE2020: usw.uri.CRMEH.NS + "EHE2020_ContextFindMeasurementEvent",
    EHE2021: usw.uri.CRMEH.NS + "EHE2021_BulkFindAssessment",
    // properties
    EHP1F: usw.uri.CRMEH.NS + "EHP1F_is_trace_of",
    EHP2F: usw.uri.CRMEH.NS + "EHP2F_is_trace_of_type",
    EHP3B: usw.uri.CRMEH.NS + "EHP3B_was_occupied_by",
    EHP3F: usw.uri.CRMEH.NS + "EHP3F_occupied",
    EHP4B: usw.uri.CRMEH.NS + "EHP4B_is_depicted_by",
    EHP4F: usw.uri.CRMEH.NS + "EHP4F_depicts",
    EHP5F: usw.uri.CRMEH.NS + "EHP5F_is_thesaurus_concept",
    EHP1003B: usw.uri.CRMEH.NS + "EHP1003B_is_note_of",
    EXP1F: usw.uri.CRMEH.NS + "EXP1F_year_min",
    EXP2F: usw.uri.CRMEH.NS + "EXP2F_.year_max",
    EXP3F: usw.uri.CRMEH.NS + "EXP3F_spatial_x",
    EXP4F: usw.uri.CRMEH.NS + "EXP4F_spatial_y",
    EXP5F: usw.uri.CRMEH.NS + "EXP5F_spatial_z",
    EXP10F: usw.uri.CRMEH.NS + "EXP10F_is_represented_by"
};

// Dublin Core
// usage: alert(usw.uri.DC.PROPERTY.TITLE) | alert(usw.uri.DC.PROPERTY["TITLE"])
// either call returns "http://purl.org/dc/elements/1.1/title"	
usw.uri.DC = { NS: "http://purl.org/dc/elements/1.1/" };
usw.uri.DC.PROPERTY = {
    // properties
    TITLE: usw.uri.DC.NS + "title",
    CREATOR: usw.uri.DC.NS + "creator",
    SUBJECT: usw.uri.DC.NS + "subject",
    DESCRIPTION: usw.uri.DC.NS + "description",
    PUBLISHER: usw.uri.DC.NS + "publisher",
    CONTRIBUTOR: usw.uri.DC.NS + "contributor",
    DATE: usw.uri.DC.NS + "date",
    TYPE: usw.uri.DC.NS + "type",
    FORMAT: usw.uri.DC.NS + "format",
    IDENTIFIER: usw.uri.DC.NS + "identifier",
    SOURCE: usw.uri.DC.NS + "source",
    LANGUAGE: usw.uri.DC.NS + "language",
    RELATION: usw.uri.DC.NS + "relation",
    COVERAGE: usw.uri.DC.NS + "coverage",
    RIGHTS: usw.uri.DC.NS + "rights"
};

// usw.uri.DCTERMS
// usage: alert(usw.uri.DCTERMS.SUBJECTSCHEME) | alert(usw.uri.DCTERMS["SUBJECTSCHEME"])
// either call returns "http://purl.org/dc/terms/SubjectScheme"		
usw.uri.DCTERMS = { NS: "http://purl.org/dc/terms/" };
usw.uri.DCTERMS = {
    // entities
    SUBJECTSCHEME: usw.uri.DCTERMS.NS + "SubjectScheme",
    DATESCHEME: usw.uri.DCTERMS.NS + "DateScheme",
    FORMATSCHEME: usw.uri.DCTERMS.NS + "FormatScheme",
    LANGUAGESCHEME: usw.uri.DCTERMS.NS + "LanguageScheme",
    SPATIALSCHEME: usw.uri.DCTERMS.NS + "SpatialScheme",
    TEMPORALSCHEME: usw.uri.DCTERMS.NS + "TemporalScheme",
    TYPESCHEME: usw.uri.DCTERMS.NS + "TypeScheme",
    IDENTIFIERSCHEME: usw.uri.DCTERMS.NS + "IdentifierScheme",
    RELATIONSCHEME: usw.uri.DCTERMS.NS + "RelationScheme",
    SOURCESCHEME: usw.uri.DCTERMS.NS + "SourceScheme",
    // properties 
    AUDIENCE: usw.uri.DCTERMS.NS + "audience",
    ALTERNATIVE: usw.uri.DCTERMS.NS + "alternative",
    TABLEOFCONTENTS: usw.uri.DCTERMS.NS + "tableOfContents",
    ABSTRACT: usw.uri.DCTERMS.NS + "abstract",
    CREATED: usw.uri.DCTERMS.NS + "created",
    VALID: usw.uri.DCTERMS.NS + "valid",
    AVAILABLE: usw.uri.DCTERMS.NS + "available",
    ISSUED: usw.uri.DCTERMS.NS + "issued",
    MODIFIED: usw.uri.DCTERMS.NS + "modified",
    EXTENT: usw.uri.DCTERMS.NS + "extent",
    MEDIUM: usw.uri.DCTERMS.NS + "medium",
    ISVERSIONOF: usw.uri.DCTERMS.NS + "isVersionOf",
    HASVERSION: usw.uri.DCTERMS.NS + "hasVersion",
    ISREPLACEDBY: usw.uri.DCTERMS.NS + "isReplacedBy",
    REPLACES: usw.uri.DCTERMS.NS + "replaces",
    ISREQUIREDBY: usw.uri.DCTERMS.NS + "isRequiredBy",
    REQUIRES: usw.uri.DCTERMS.NS + "requires",
    ISPARTOF: usw.uri.DCTERMS.NS + "isPartOf",
    HASPART: usw.uri.DCTERMS.NS + "hasPart",
    ISREFERENCEDBY: usw.uri.DCTERMS.NS + "isReferencedBy",
    REFERENCES: usw.uri.DCTERMS.NS + "references",
    ISFORMATOF: usw.uri.DCTERMS.NS + "isFormatOf",
    HASFORMAT: usw.uri.DCTERMS.NS + "hasFormat",
    CONFORMSTO: usw.uri.DCTERMS.NS + "conformsTo",
    SPATIAL: usw.uri.DCTERMS.NS + "spatial",
    TEMPORAL: usw.uri.DCTERMS.NS + "temporal",
    MEDIATOR: usw.uri.DCTERMS.NS + "mediator",
    DATEACCEPTED: usw.uri.DCTERMS.NS + "dateAccepted",
    DATECOPYRIGHTED: usw.uri.DCTERMS.NS + "dateCopyrighted",
    DATESUBMITTED: usw.uri.DCTERMS.NS + "dateSubmitted",
    EDUCATIONLEVEL: usw.uri.DCTERMS.NS + "educationLevel",
    ACCESSRIGHTS: usw.uri.DCTERMS.NS + "accessRights",
    BIBLIOGRAPHICCITATION: usw.uri.DCTERMS.NS + "bibliographicCitation",
    LICENSE: usw.uri.DCTERMS.NS + "license",
    RIGHTSHOLDER: usw.uri.DCTERMS.NS + "rightsHolder",
    PROVENANCE: usw.uri.DCTERMS.NS + "provenance",
    INSTRUCTIONALMETHOD: usw.uri.DCTERMS.NS + "instructionalMethod",
    ACCRUALMETHOD: usw.uri.DCTERMS.NS + "accrualMethod",
    ACCRUALPERIODICITY: usw.uri.DCTERMS.NS + "accrualPeriodicity",
    ACCRUALPOLICY: usw.uri.DCTERMS.NS + "accrualPolicy"
};

// usw.uri.OWL
// usage: alert(usw.uri.OWL.ALLDIFFERENT) | alert(usw.uri.OWL["ALLDIFFERENT"])
// either call returns "http://www.w3.org/2002/07/owl#AllDifferent"	
usw.uri.OWL = { NS: "http://www.w3.org/2002/07/owl#" };
usw.uri.OWL = {
    // entities
    ALLDIFFERENT: usw.uri.OWL.NS + "AllDifferent",
    ANNOTATIONPROPERTY: usw.uri.OWL.NS + "AnnotationProperty",
    CLASS: usw.uri.OWL.NS + "Class",
    DATARANGE: usw.uri.OWL.NS + "DataRange",
    DATATYPEPROPERTY: usw.uri.OWL.NS + "DatatypeProperty",
    DEPRECATEDCLASS: usw.uri.OWL.NS + "DeprecatedClass",
    DEPRECATEDPROPERTY: usw.uri.OWL.NS + "DeprecatedProperty",
    FUNCTIONALPROPERTY: usw.uri.OWL.NS + "FunctionalProperty",
    INVERSEFUNCTIONALPROPERTY: usw.uri.OWL.NS + "InverseFunctionalProperty",
    NOTHING: usw.uri.OWL.NS + "Nothing",
    OBJECTPROPERTY: usw.uri.OWL.NS + "ObjectProperty",
    ONTOLOGY: usw.uri.OWL.NS + "Ontology",
    ONTOLOGYPROPERTY: usw.uri.OWL.NS + "OntologyProperty",
    RESTRICTION: usw.uri.OWL.NS + "Restriction",
    SYMMETRICPROPERTY: usw.uri.OWL.NS + "SymmetricProperty",
    THING: usw.uri.OWL.NS + "Thing",
    TRANSITIVEPROPERTY: usw.uri.OWL.NS + "TransitiveProperty",
    // properties
    ALLVALUESFROM: usw.uri.OWL.NS + "allValuesFrom",
    BACKWARDCOMPATIBLEWITH: usw.uri.OWL.NS + "backwardCompatibleWith",
    CARDINALITY: usw.uri.OWL.NS + "cardinality",
    COMPLEMENTOF: usw.uri.OWL.NS + "complementOf",
    DIFFERENTFROM: usw.uri.OWL.NS + "differentFrom",
    DISJOINTWITH: usw.uri.OWL.NS + "disjointWith",
    DISTINCTMEMBERS: usw.uri.OWL.NS + "distinctMembers",
    EQUIVALENTCLASS: usw.uri.OWL.NS + "equivalentClass",
    EQUIVALENTPROPERTY: usw.uri.OWL.NS + "equivalentProperty",
    HASVALUE: usw.uri.OWL.NS + "hasValue",
    IMPORTS: usw.uri.OWL.NS + "imports",
    INCOMPATIBLEWITH: usw.uri.OWL.NS + "incompatibleWith",
    INTERSECTIONOF: usw.uri.OWL.NS + "intersectionOf",
    INVERSEOF: usw.uri.OWL.NS + "inverseOf",
    MAXCARDINALITY: usw.uri.OWL.NS + "maxCardinality",
    MINCARDINALITY: usw.uri.OWL.NS + "minCardinality",
    ONEOF: usw.uri.OWL.NS + "oneOf",
    ONPROPERTY: usw.uri.OWL.NS + "onProperty",
    PRIORVERSION: usw.uri.OWL.NS + "priorVersion",
    SAMEAS: usw.uri.OWL.NS + "sameAs",
    SOMEVALUESFROM: usw.uri.OWL.NS + "someValuesFrom",
    UNIONOF: usw.uri.OWL.NS + "unionOf",
    VERSIONINFO: usw.uri.OWL.NS + "versionInfo"
};

// usw.uri.CRM - represents version 5.0.4 of CIDOC CRM
usw.uri.CRM = { NS: "http://www.cidoc-crm.org/cidoc-crm/" };
usw.uri.CRM = {
    // entities
    E1: usw.uri.CRM.NS + "E1_CRM_Entity",
    E2: usw.uri.CRM.NS + "E2_Temporal_Entity",
    E3: usw.uri.CRM.NS + "E3_Condition_State",
    E4: usw.uri.CRM.NS + "E4_Period",
    E5: usw.uri.CRM.NS + "E5_Event",
    E6: usw.uri.CRM.NS + "E6_Destruction",
    E7: usw.uri.CRM.NS + "E7_Activity",
    E8: usw.uri.CRM.NS + "E8_Acquisition",
    E9: usw.uri.CRM.NS + "E9_Move",
    E10: usw.uri.CRM.NS + "E10_Transfer_of_Custody",
    E11: usw.uri.CRM.NS + "E11_Modification",
    E12: usw.uri.CRM.NS + "E12_Production",
    E13: usw.uri.CRM.NS + "E13_Attribute_Assignment",
    E14: usw.uri.CRM.NS + "E14_Condition_Assessment",
    E15: usw.uri.CRM.NS + "E15_Identifier_Assignment",
    E16: usw.uri.CRM.NS + "E16_Measurement",
    E17: usw.uri.CRM.NS + "E17_Type_Assignment",
    E18: usw.uri.CRM.NS + "E18_Physical_Thing",
    E19: usw.uri.CRM.NS + "E19_Physical_Object",
    E20: usw.uri.CRM.NS + "E20_Biological_Object",
    E21: usw.uri.CRM.NS + "E21_Person",
    E22: usw.uri.CRM.NS + "E22_Man-Made_Object",
    E24: usw.uri.CRM.NS + "E24_Physical_Man-Made_Thing",
    E25: usw.uri.CRM.NS + "E25_Man-Made_Feature",
    E26: usw.uri.CRM.NS + "E26_Physical_Feature",
    E27: usw.uri.CRM.NS + "E27_Site",
    E28: usw.uri.CRM.NS + "E28_Conceptual_Object",
    E29: usw.uri.CRM.NS + "E29_Design_or_Procedure",
    E30: usw.uri.CRM.NS + "E30_Right",
    E31: usw.uri.CRM.NS + "E31_Document",
    E32: usw.uri.CRM.NS + "E32_Authority_Document",
    E33: usw.uri.CRM.NS + "E33_Linguistic_Object",
    E34: usw.uri.CRM.NS + "E34_Inscription",
    E35: usw.uri.CRM.NS + "E35_Title",
    E36: usw.uri.CRM.NS + "E36_Visual_Item",
    E37: usw.uri.CRM.NS + "E37_Mark",
    E38: usw.uri.CRM.NS + "E38_Image",
    E39: usw.uri.CRM.NS + "E39_Actor",
    E40: usw.uri.CRM.NS + "E40_Legal_Body",
    E41: usw.uri.CRM.NS + "E41_Appellation",
    E42: usw.uri.CRM.NS + "E42_Identifier",
    E44: usw.uri.CRM.NS + "E44_Place_Appellation",
    E45: usw.uri.CRM.NS + "E45_Address",
    E46: usw.uri.CRM.NS + "E46_Section_Definition",
    E47: usw.uri.CRM.NS + "E47_Spatial_Coordinates",
    E48: usw.uri.CRM.NS + "E48_Place_Name",
    E49: usw.uri.CRM.NS + "E49_Time_Appellation",
    E50: usw.uri.CRM.NS + "E50_Date",
    E51: usw.uri.CRM.NS + "E51_Contact_Point",
    E52: usw.uri.CRM.NS + "E52_Time-Span",
    E53: usw.uri.CRM.NS + "E53_Place",
    E54: usw.uri.CRM.NS + "E54_Dimension",
    E55: usw.uri.CRM.NS + "E55_Type",
    E56: usw.uri.CRM.NS + "E56_Language",
    E57: usw.uri.CRM.NS + "E57_Material",
    E58: usw.uri.CRM.NS + "E58_Measurement_Unit",
    E59: usw.uri.CRM.NS + "E59_PrimitiveValue",
    E60: usw.uri.CRM.NS + "E60_Number",
    E61: usw.uri.CRM.NS + "E61_Time_Primitive",
    E62: usw.uri.CRM.NS + "E62_String",
    E63: usw.uri.CRM.NS + "E63_Beginning_of_Existence",
    E64: usw.uri.CRM.NS + "E64_End_of_Existence",
    E65: usw.uri.CRM.NS + "E65_Creation",
    E66: usw.uri.CRM.NS + "E66_Formation",
    E67: usw.uri.CRM.NS + "E67_Birth",
    E68: usw.uri.CRM.NS + "E68_Dissolution",
    E69: usw.uri.CRM.NS + "E69_Death",
    E70: usw.uri.CRM.NS + "E70_Thing",
    E71: usw.uri.CRM.NS + "E71_Man-Made_Thing",
    E72: usw.uri.CRM.NS + "E72_Legal_Object",
    E73: usw.uri.CRM.NS + "E73_Information_Object",
    E74: usw.uri.CRM.NS + "E74_Group",
    E75: usw.uri.CRM.NS + "E75_Conceptual_Object_Appellation",
    E77: usw.uri.CRM.NS + "E77_Persistent_Item",
    E78: usw.uri.CRM.NS + "E78_Collection",
    E79: usw.uri.CRM.NS + "E79_Part_Addition",
    E80: usw.uri.CRM.NS + "E80_Part_Removal",
    E81: usw.uri.CRM.NS + "E81_Transformation",
    E82: usw.uri.CRM.NS + "E82_Actor_Appellation",
    E83: usw.uri.CRM.NS + "E83_Type_Creation",
    E84: usw.uri.CRM.NS + "E84_Information_Carrier",
    E85: usw.uri.CRM.NS + "E85_Joining",
    E86: usw.uri.CRM.NS + "E86_Leaving",
    E87: usw.uri.CRM.NS + "E87_Curation_Activity",
    E89: usw.uri.CRM.NS + "E89_Propositional_Object",
    E90: usw.uri.CRM.NS + "E90_Symbolic_Object",
    // properties
    P1: usw.uri.CRM.NS + "P1_is_identified_by",
    P1i: usw.uri.CRM.NS + "P1i_identifies",
    P2: usw.uri.CRM.NS + "P2_has_type",
    P2i: usw.uri.CRM.NS + "P2i_is_type_of",
    P3: usw.uri.CRM.NS + "P3_has_note",
    P4: usw.uri.CRM.NS + "P4_has_time-span",
    P4i: usw.uri.CRM.NS + "P4i_is_time-span_of",
    P5: usw.uri.CRM.NS + "P5_consists_of",
    P5i: usw.uri.CRM.NS + "P5i_forms_part_of",
    P7: usw.uri.CRM.NS + "P7_took_place_at",
    P7i: usw.uri.CRM.NS + "P7i_witnessed",
    P8: usw.uri.CRM.NS + "P8_took_place_on_or_within",
    P8i: usw.uri.CRM.NS + "P8i_witnessed",
    P9: usw.uri.CRM.NS + "P9_consists_of",
    P9i: usw.uri.CRM.NS + "P9i_forms_part_of",
    P10: usw.uri.CRM.NS + "P10_falls_within",
    P10i: usw.uri.CRM.NS + "P10i_contains",
    P11: usw.uri.CRM.NS + "P11_had_participant",
    P11i: usw.uri.CRM.NS + "P11i_participated_in",
    P12: usw.uri.CRM.NS + "P12_occurred_in_the_presence_of",
    P12i: usw.uri.CRM.NS + "P12i_was_present_at",
    P13: usw.uri.CRM.NS + "P13_destroyed",
    P13i: usw.uri.CRM.NS + "P13i_was_destroyed_by",
    P14: usw.uri.CRM.NS + "P14_carried_out_by",
    P14i: usw.uri.CRM.NS + "P14i_performed",
    P15: usw.uri.CRM.NS + "P15_was_influenced_by",
    P15i: usw.uri.CRM.NS + "P15i_influenced",
    P16: usw.uri.CRM.NS + "P16_used_specific_object",
    P16i: usw.uri.CRM.NS + "P16i_was_used_for",
    P17: usw.uri.CRM.NS + "P17_was_motivated_by",
    P17i: usw.uri.CRM.NS + "P17i_motivated",
    P19: usw.uri.CRM.NS + "P19_was_intended_use_of",
    P19i: usw.uri.CRM.NS + "P19i_was_made_for",
    P20: usw.uri.CRM.NS + "P20_had_specific_purpose",
    P20i: usw.uri.CRM.NS + "P20i_was_purpose_of",
    P21: usw.uri.CRM.NS + "P21_had_general_purpose",
    P21i: usw.uri.CRM.NS + "P21i_was_purpose_of",
    P22: usw.uri.CRM.NS + "P22_transferred_title_to",
    P22i: usw.uri.CRM.NS + "P22i_acquired_title_through",
    P23: usw.uri.CRM.NS + "P23_transferred_title_from",
    P23i: usw.uri.CRM.NS + "P23i_surrendered_title_through",
    P24: usw.uri.CRM.NS + "P24_transferred_title_of",
    P24i: usw.uri.CRM.NS + "P24i_changed_ownership_through",
    P25: usw.uri.CRM.NS + "P25_moved",
    P25i: usw.uri.CRM.NS + "P25i_moved_by",
    P26: usw.uri.CRM.NS + "P26_moved_to",
    P26i: usw.uri.CRM.NS + "P26i_was_destination_of",
    P27: usw.uri.CRM.NS + "P27_moved_from",
    P27i: usw.uri.CRM.NS + "P27i_was_origin_of",
    P28: usw.uri.CRM.NS + "P28_custody_surrendered_by",
    P28i: usw.uri.CRM.NS + "P28i_surrendered_custody_through",
    P29: usw.uri.CRM.NS + "P29_custody_received_by",
    P29i: usw.uri.CRM.NS + "P29i_received_custody_through",
    P30: usw.uri.CRM.NS + "P30_transferred_custody_of",
    P30i: usw.uri.CRM.NS + "P30i_custody_transferred_through",
    P31: usw.uri.CRM.NS + "P31_has_modified",
    P31i: usw.uri.CRM.NS + "P31i_was_modified_by",
    P32: usw.uri.CRM.NS + "P32_used_general_technique",
    P32i: usw.uri.CRM.NS + "P32i_was_technique_of",
    P33: usw.uri.CRM.NS + "P33_used_specific_technique",
    P33i: usw.uri.CRM.NS + "P33i_was_used_by",
    P34: usw.uri.CRM.NS + "P34_concerned",
    P34i: usw.uri.CRM.NS + "P34i_was_assessed_by",
    P35: usw.uri.CRM.NS + "P35_has_identified",
    P35i: usw.uri.CRM.NS + "P35i_was_identified_by",
    P37: usw.uri.CRM.NS + "P37_assigned",
    P37i: usw.uri.CRM.NS + "P37i_was_assigned_by",
    P38: usw.uri.CRM.NS + "P38_deassigned",
    P38i: usw.uri.CRM.NS + "P38i_was_deassigned_by",
    P39: usw.uri.CRM.NS + "P39_measured",
    P39i: usw.uri.CRM.NS + "P39i_was_measured_by",
    P40: usw.uri.CRM.NS + "P40_observed_dimension",
    P40i: usw.uri.CRM.NS + "P40i_was_observed_in",
    P41: usw.uri.CRM.NS + "P41_classified",
    P41i: usw.uri.CRM.NS + "P41i_was_classified_by",
    P42: usw.uri.CRM.NS + "P42_assigned",
    P42i: usw.uri.CRM.NS + "P42i_was_assigned_by",
    P43: usw.uri.CRM.NS + "P43_has_dimension",
    P43i: usw.uri.CRM.NS + "P43i_is_dimension_of",
    P44: usw.uri.CRM.NS + "P44_has_condition",
    P44i: usw.uri.CRM.NS + "P44i_condition_of",
    P45: usw.uri.CRM.NS + "P45_consists_of",
    P45i: usw.uri.CRM.NS + "P45i_is_incorporated_in",
    P46: usw.uri.CRM.NS + "P46_is_composed_of",
    P46i: usw.uri.CRM.NS + "P46i_forms_part_of",
    P48: usw.uri.CRM.NS + "P48_has_preferred_identifier",
    P48i: usw.uri.CRM.NS + "P48i_is_preferred_identifier_of",
    P49: usw.uri.CRM.NS + "P49_has_former_or_current_keeper",
    P49i: usw.uri.CRM.NS + "P49i_is_former_or_current_keeper_of",
    P50: usw.uri.CRM.NS + "P50_has_current_keeper",
    P50i: usw.uri.CRM.NS + "P50i_is_current_keeper_of",
    P51: usw.uri.CRM.NS + "P51_has_former_or_current_owner",
    P51i: usw.uri.CRM.NS + "P51i_is_former_or_current_owner_of",
    P52: usw.uri.CRM.NS + "P52_has_current_owner",
    P52i: usw.uri.CRM.NS + "P52i_is_current_owner_of",
    P53: usw.uri.CRM.NS + "P53_has_former_or_current_location",
    P53i: usw.uri.CRM.NS + "P53i_is_former_or_current_location_of",
    P54: usw.uri.CRM.NS + "P54_has_current_permanent_location",
    P54i: usw.uri.CRM.NS + "P54i_is_current_permanent_location_of",
    P55: usw.uri.CRM.NS + "P55_has_current_location",
    P55i: usw.uri.CRM.NS + "P55i_currently_holds",
    P56: usw.uri.CRM.NS + "P56_bears_feature",
    P56i: usw.uri.CRM.NS + "P56i_is_found_on",
    P57: usw.uri.CRM.NS + "P57_has_number_of_parts",
    P58: usw.uri.CRM.NS + "P58_has_section_definition",
    P58i: usw.uri.CRM.NS + "P58i_defines_section",
    P59: usw.uri.CRM.NS + "P59_has_section",
    P59i: usw.uri.CRM.NS + "P59i_is_located_on_or_within",
    P62: usw.uri.CRM.NS + "P62_depicts",
    P62i: usw.uri.CRM.NS + "P62i_is_depicted_by",
    P65: usw.uri.CRM.NS + "P65_shows_visual_item",
    P65i: usw.uri.CRM.NS + "P65i_is_shown_by",
    P67: usw.uri.CRM.NS + "P67_refers_to",
    P67i: usw.uri.CRM.NS + "P67i_is_referred_to_by",
    P68: usw.uri.CRM.NS + "P68_foresees_use_of",
    P68i: usw.uri.CRM.NS + "P68i_use_foreseen_by",
    P69: usw.uri.CRM.NS + "P69_is_associated_with",
    P70: usw.uri.CRM.NS + "P70_documents",
    P70i: usw.uri.CRM.NS + "P70i_is_documented_in",
    P71: usw.uri.CRM.NS + "P71_lists",
    P71i: usw.uri.CRM.NS + "P71i_is_listed_in",
    P72: usw.uri.CRM.NS + "P72_has_language",
    P72i: usw.uri.CRM.NS + "P72i_is_language_of",
    P73: usw.uri.CRM.NS + "P73_has_translation",
    P73i: usw.uri.CRM.NS + "P73i_is_translation_of",
    P74: usw.uri.CRM.NS + "P74_has_current_or_former_residence",
    P74i: usw.uri.CRM.NS + "P74i_is_current_or_former_residence_of",
    P75: usw.uri.CRM.NS + "P75_possesses",
    P75i: usw.uri.CRM.NS + "P75i_is_possessed_by",
    P76: usw.uri.CRM.NS + "P76_has_contact_point",
    P76i: usw.uri.CRM.NS + "P76i_provides_access_to",
    P78: usw.uri.CRM.NS + "P78_is_identified_by",
    P78i: usw.uri.CRM.NS + "P78i_identifies",
    P79: usw.uri.CRM.NS + "P79_beginning_is_qualified_by",
    P80: usw.uri.CRM.NS + "P80_end_is_qualified_by",
    P81: usw.uri.CRM.NS + "P81_ongoing_throughout",
    P82: usw.uri.CRM.NS + "P82_at_some_time_within",
    P83: usw.uri.CRM.NS + "P83_had_at_least_duration",
    P83i: usw.uri.CRM.NS + "P83i_was_minimum_duration_of",
    P84: usw.uri.CRM.NS + "P84_had_at_most_duration",
    P84i: usw.uri.CRM.NS + "P84i_was_maximum_duration_of",
    P86: usw.uri.CRM.NS + "P86_falls_within",
    P86i: usw.uri.CRM.NS + "P86i_contains",
    P87: usw.uri.CRM.NS + "P87_is_identified_by",
    P87i: usw.uri.CRM.NS + "P87i_identifies",
    P88: usw.uri.CRM.NS + "P88_consists_of",
    P88i: usw.uri.CRM.NS + "P88i_forms_part_of",
    P89: usw.uri.CRM.NS + "P89_falls_within",
    P89i: usw.uri.CRM.NS + "P89i_contains",
    P90: usw.uri.CRM.NS + "P90_has_value",
    P91: usw.uri.CRM.NS + "P91_has_unit",
    P91i: usw.uri.CRM.NS + "P91i_is_unit_of",
    P92: usw.uri.CRM.NS + "P92_brought_into_existence",
    P92i: usw.uri.CRM.NS + "P92i_was_brought_into_existence_by",
    P93: usw.uri.CRM.NS + "P93_took_out_of_existence",
    P93i: usw.uri.CRM.NS + "P93i_was_taken_out_of_existence_by",
    P94: usw.uri.CRM.NS + "P94_has_created",
    P94i: usw.uri.CRM.NS + "P94i_was_created_by",
    P95: usw.uri.CRM.NS + "P95_has_formed",
    P95i: usw.uri.CRM.NS + "P95i_was_formed_by",
    P96: usw.uri.CRM.NS + "P96_by_mother",
    P96i: usw.uri.CRM.NS + "P96i_gave_birth",
    P97: usw.uri.CRM.NS + "P97_from_father",
    P97i: usw.uri.CRM.NS + "P97i_was_father_for",
    P98: usw.uri.CRM.NS + "P98_brought_into_life",
    P98i: usw.uri.CRM.NS + "P98i_was_born",
    P99: usw.uri.CRM.NS + "P99_dissolved",
    P99i: usw.uri.CRM.NS + "P99i_was_dissolved_by",
    P100: usw.uri.CRM.NS + "P100_was_death_of",
    P100i: usw.uri.CRM.NS + "P100i_died_in",
    P101: usw.uri.CRM.NS + "P101_had_as_general_use",
    P101i: usw.uri.CRM.NS + "P101i_was_use_of",
    P102: usw.uri.CRM.NS + "P102_has_title",
    P102i: usw.uri.CRM.NS + "P102i_is_title_of",
    P103: usw.uri.CRM.NS + "P103_was_intended_for",
    P103i: usw.uri.CRM.NS + "P103i_was_intention_of",
    P104: usw.uri.CRM.NS + "P104_is_subject_to",
    P104i: usw.uri.CRM.NS + "P104i_applies_to",
    P105: usw.uri.CRM.NS + "P105_right_held_by",
    P105i: usw.uri.CRM.NS + "P105i_has_right_on",
    P106: usw.uri.CRM.NS + "P106_is_composed_of",
    P106i: usw.uri.CRM.NS + "P106i_forms_part_of",
    P107: usw.uri.CRM.NS + "P107_has_current_or_former_member",
    P107i: usw.uri.CRM.NS + "P107i_is_current_or_former_member_of",
    P108: usw.uri.CRM.NS + "P108_has_produced",
    P108i: usw.uri.CRM.NS + "P108i_was_produced_by",
    P109: usw.uri.CRM.NS + "P109_has_current_or_former_curator",
    P109i: usw.uri.CRM.NS + "P109i_is_current_or_former_curator_of",
    P110: usw.uri.CRM.NS + "P110_augmented",
    P110i: usw.uri.CRM.NS + "P110i_was_augmented_by",
    P111: usw.uri.CRM.NS + "P111_added",
    P111i: usw.uri.CRM.NS + "P111i_was_added_by",
    P112: usw.uri.CRM.NS + "P112_diminished",
    P112i: usw.uri.CRM.NS + "P112i_was_diminished_by",
    P113: usw.uri.CRM.NS + "P113_removed",
    P113i: usw.uri.CRM.NS + "P113i_was_removed_by",
    P114: usw.uri.CRM.NS + "P114_is_equal_in_time_to",
    P115: usw.uri.CRM.NS + "P115_finishes",
    P115i: usw.uri.CRM.NS + "P115i_is_finished_by",
    P116: usw.uri.CRM.NS + "P116_starts",
    P116i: usw.uri.CRM.NS + "P116i_is_started_by",
    P117: usw.uri.CRM.NS + "P117_occurs_during",
    P117i: usw.uri.CRM.NS + "P117i_includes",
    P118: usw.uri.CRM.NS + "P118_overlaps_in_time_with",
    P118i: usw.uri.CRM.NS + "P118i_is_overlapped_in_time_by",
    P119: usw.uri.CRM.NS + "P119_meets_in_time_with",
    P119i: usw.uri.CRM.NS + "P119i_is_met_in_time_by",
    P120: usw.uri.CRM.NS + "P120_occurs_before",
    P120i: usw.uri.CRM.NS + "P120i_occurs_after",
    P121: usw.uri.CRM.NS + "P121_overlaps_with",
    P122: usw.uri.CRM.NS + "P122_borders_with",
    P123: usw.uri.CRM.NS + "P123_resulted_in",
    P123i: usw.uri.CRM.NS + "P123i_resulted_from",
    P124: usw.uri.CRM.NS + "P124_transformed",
    P124i: usw.uri.CRM.NS + "P124i_was_transformed_by",
    P125: usw.uri.CRM.NS + "P125_used_object_of_type",
    P125i: usw.uri.CRM.NS + "P125i_was_type_of_object_used_in",
    P126: usw.uri.CRM.NS + "P126_employed",
    P126i: usw.uri.CRM.NS + "P126i_was_employed_in",
    P127: usw.uri.CRM.NS + "P127_has_broader_term",
    P127i: usw.uri.CRM.NS + "P127i_has_narrower_term",
    P128: usw.uri.CRM.NS + "P128_carries",
    P128i: usw.uri.CRM.NS + "P128i_is_carried_by",
    P129: usw.uri.CRM.NS + "P129_is_about",
    P129i: usw.uri.CRM.NS + "P129i_is_subject_of",
    P130: usw.uri.CRM.NS + "P130_shows_features_of",
    P130i: usw.uri.CRM.NS + "P130i_features_are_also_found_on",
    P131: usw.uri.CRM.NS + "P131_is_identified_by",
    P131i: usw.uri.CRM.NS + "P131i_identifies",
    P132: usw.uri.CRM.NS + "P132_overlaps_with",
    P133: usw.uri.CRM.NS + "P133_is_separated_from",
    P134: usw.uri.CRM.NS + "P134_continued",
    P134i: usw.uri.CRM.NS + "P134i_was_continued_by",
    P135: usw.uri.CRM.NS + "P135_created_type",
    P135i: usw.uri.CRM.NS + "P135i_was_created_by",
    P136: usw.uri.CRM.NS + "P136_was_based_on",
    P136i: usw.uri.CRM.NS + "P136i_supported_type_creation",
    P137: usw.uri.CRM.NS + "P137_exemplifies",
    P137i: usw.uri.CRM.NS + "P137i_is_exemplified_by",
    P138: usw.uri.CRM.NS + "P138_represents",
    P138i: usw.uri.CRM.NS + "P138i_has_representation",
    P139: usw.uri.CRM.NS + "P139_has_alternative_form",
    P140: usw.uri.CRM.NS + "P140_assigned_attribute_to",
    P140i: usw.uri.CRM.NS + "P140i_was_attributed_by",
    P141: usw.uri.CRM.NS + "P141_assigned",
    P141i: usw.uri.CRM.NS + "P141i_was_assigned_by",
    P142: usw.uri.CRM.NS + "P142_used_constituent",
    P142i: usw.uri.CRM.NS + "P142i_was_used_in",
    P143: usw.uri.CRM.NS + "P143_joined",
    P143i: usw.uri.CRM.NS + "P143i_was_joined_by",
    P144: usw.uri.CRM.NS + "P144_joined_with",
    P144i: usw.uri.CRM.NS + "P144i_gained_member_by",
    P145: usw.uri.CRM.NS + "P145_separated",
    P145i: usw.uri.CRM.NS + "P145i_left_by",
    P146: usw.uri.CRM.NS + "P146_separated_from",
    P146i: usw.uri.CRM.NS + "P146i_lost_member_by",
    P147: usw.uri.CRM.NS + "P147_curated",
    P147i: usw.uri.CRM.NS + "P147i_was_curated_by",
    P148: usw.uri.CRM.NS + "P148_has_component",
    P148i: usw.uri.CRM.NS + "P148i_is_component_of",
    P149: usw.uri.CRM.NS + "P149_is_identified_by",
    P149i: usw.uri.CRM.NS + "P149i_identifies"
};
